#!/usr/bin/env python3
"""Generate the aggressive TLD layer and the exclusions layer from the allowlist.

Single source of truth is src/allowlist-io.txt. It feeds two outputs:
  src/aggressive-tlds.txt  -> ||<tld>^$denyallow=a|b|c   (the block rules)
  src/exclusions.txt       -> regexes that strip those domains from upstreams

Why $denyallow rather than a bare ||io^ plus @@ exception rules:
  - hostlist-compiler's Validate transformation DELETES any rule whose pattern
    is exactly a public suffix (||io^), unless it carries an exempting modifier:
    denyallow, badfilter or client. Verified in
    HostlistCompiler/src/transformations/validate.js (v2.1.0).
  - One rule instead of one block plus N exceptions.
  - A plain @@ exception can be overridden by an upstream $important rule;
    $denyallow inside the rule itself cannot.

CAVEAT - verify on your instance: the ||-anchored + $denyallow combination is
documented for DNS filtering (https://adguard-dns.io/kb/general/dns-filtering-syntax/
gives ||example.org^$denyallow=sub.example.org) but AdGuard's *ad blocker* docs
state a $denyallow pattern "cannot start with ||". Two engines, two docs that
disagree. For AdGuard Home the DNS doc governs, but confirm via
Settings -> Check the filtering. README documents the fallback form.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# TLDs where effectively all traffic is browser games.
# Evidence: of 52 live game domains missed by all 5 stacked upstream lists,
# 50 were .io. See tests/known-game-domains.txt.
GAME_TLDS = ['io', 'games', 'game', 'gg', 'lol', 'fun', 'onl']

# Generic TLDs with real legitimate use. Each catches only a couple more game
# sites at meaningful collateral cost, so these ship commented out.
HIGH_COLLATERAL_TLDS = ['online', 'space']

# Confirmed false positives in upstream lists, each traced to its source and
# verified by hand. These are stripped from the compiled output.
UPSTREAM_FALSE_POSITIVES = [
    # --- Infrastructure: blocking these breaks unrelated software ---
    'cloudfront.net',   # Josuha - ALL of Amazon CloudFront. Breaks much of the web.
    'nvidia.com',       # UT1 - breaks driver downloads. gfn.nvidia.com stays blocked.
    'playstation.net',  # UT1 - breaks PSN sign-in. remoteplay.dl.* stays blocked.
    'sentry.io',        # Josuha line 1231 - error monitoring, not a game
    # --- Breaks non-gaming platform functions ---
    # UT1 blocks play.google.com. That stops ALL Android app installs and
    # security updates network-wide, not just games. If you actually want the
    # Play Store closed as a parental lever, delete this line and rebuild, or
    # better, use AdGuard Home's Blocked Services which scopes per-client.
    'play.google.com',
    # --- Educational / ML, wrongly categorised upstream ---
    'huggingface.co',   # IREK-szef, and NemesisHubris which re-imports it
    'khanacademy.org',  # NemesisHubris
]

# Deliberately NOT excluded, though upstream blocks them: xbox.com, xboxlive.com,
# playstation.com, steampowered.com, roblox.com, epicgames.com, minecraft.net,
# chess.com, itch.io, scratch.mit.edu. These are real game platforms and an
# aggressive list should block them. Use AdGuard Home's Blocked Services
# (gaming group, 22 services) if you would rather toggle them individually.


def read_allowlist(path):
    if not path.exists():
        return []
    out = []
    for line in path.read_text(encoding='utf-8').splitlines():
        line = line.strip()
        if line and not line.startswith('!'):
            out.append(line)
    return sorted(set(out))


def rule_for(tld, allow):
    scoped = [d for d in allow if d.endswith('.' + tld)]
    if scoped:
        return '||{}^$denyallow={}'.format(tld, '|'.join(scoped))
    return '||{}^'.format(tld)


def write_tlds(allow):
    lines = [
        '! Aggressive layer: whole-TLD blocking for game-dominated TLDs.',
        '! Generated by scripts/gen_tld_rules.py - do not edit by hand.',
        '! Exemptions come from src/allowlist-io.txt ({} entries).'.format(len(allow)),
        '!',
    ]
    lines += [rule_for(t, allow) for t in GAME_TLDS]
    lines += [
        '!',
        '! --- High collateral damage: uncomment deliberately ---',
        '! Substantial legitimate use on these. Each catches only a few extra',
        '! game sites. Enable only if you accept breaking unrelated sites.',
    ]
    lines += ['! ' + rule_for(t, allow) for t in HIGH_COLLATERAL_TLDS]

    out = ROOT / 'src' / 'aggressive-tlds.txt'
    out.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print('wrote {}: {} active TLD rules, {} commented, {} exemptions'.format(
        out.relative_to(ROOT), len(GAME_TLDS), len(HIGH_COLLATERAL_TLDS), len(allow)))


def write_exclusions(allow):
    r"""Emit anchored regex exclusions for hostlist-compiler.

    MEASURED BEHAVIOUR, not what the docs imply: exclusions are matched against
    each source's ORIGINAL line format, BEFORE the Compress transformation runs.
    Verified 2026-09-10 - an exclusion of /^\|\|nvidia\.com\^$/ failed to strip
    'nvidia.com' arriving as a bare domain from UT1, while the same pattern did
    strip '||cloudfront.net^' arriving already in adblock form from Josuha.
    The HostlistCompiler README advises adding Compress so exclusions match
    format, which suggests the reverse order; it does not hold here.

    So every domain gets three patterns, one per source format:
      ||domain^      adblock sources
      domain         bare domain-list sources
      0.0.0.0 domain /etc/hosts sources

    Anchored regex rather than hostlist-compiler's default substring matching,
    because a plainstring exclusion of 'sentry.io' would also strip
    '||mysentry.io^'.
    """
    domains = sorted(set(allow) | set(UPSTREAM_FALSE_POSITIVES))
    lines = [
        '! Rules stripped from the compiled output.',
        '! Generated by scripts/gen_tld_rules.py - do not edit by hand.',
        '! Anchored regex, matched after Compress normalises to ||domain^.',
        '!',
    ]
    for d in domains:
        e = d.replace('.', r'\.')
        lines.append(r'/^\|\|' + e + r'\^$/')          # adblock form
        lines.append(r'/^' + e + r'$/')                  # bare domain form
        lines.append(r'/^\S+\s+' + e + r'\s*$/')        # hosts form

    out = ROOT / 'src' / 'exclusions.txt'
    out.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print('wrote {}: {} exclusion patterns'.format(out.relative_to(ROOT), len(domains)))


def main():
    allow = read_allowlist(ROOT / 'src' / 'allowlist-io.txt')
    write_tlds(allow)
    write_exclusions(allow)
    return 0


if __name__ == '__main__':
    sys.exit(main())
